version: '3'

services:
  api:
    build: .
    ports:
      - "8010:8010"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    # volumes:
    #   - ./data:/data/db
    ports:
      - "27017:27017"